# Generated by Django 3.1.12 on 2025-04-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdData',
            fields=[
                ('household_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Unique Household Identifier')),
                ('voltage', models.FloatField(help_text='Voltage measurement in Volts', verbose_name='Electrical Voltage')),
                ('current', models.FloatField(help_text='Current measurement in Amperes', verbose_name='Electrical Current')),
                ('power_consumption', models.FloatField(help_text='Power consumption in kilowatts (kW)', verbose_name='Total Power Consumption')),
                ('solar_power', models.FloatField(default=0.0, help_text='Solar power generation in kilowatts (kW)', verbose_name='Solar Power Generation')),
                ('wind_power', models.FloatField(default=0.0, help_text='Wind power generation in kilowatts (kW)', verbose_name='Wind Power Generation')),
                ('grid_supply', models.FloatField(help_text='Power supplied from the electrical grid in kilowatts (kW)', verbose_name='Grid Power Supply')),
                ('overload_condition', models.BooleanField(default=False, help_text='Indicates whether the system is experiencing an overload', verbose_name='Overload Status')),
                ('transformer_fault', models.BooleanField(default=False, help_text='Indicates the presence of a transformer fault', verbose_name='Transformer Fault')),
                ('temperature', models.FloatField(help_text='Temperature in degrees Celsius', verbose_name='Ambient Temperature')),
                ('humidity', models.FloatField(help_text='Humidity percentage', verbose_name='Humidity Level')),
                ('electricity_price', models.FloatField(help_text='Price of electricity per kilowatt-hour', verbose_name='Electricity Price')),
                ('predicted_load', models.FloatField(help_text='Predicted energy load in kilowatts (kW)', verbose_name='Predicted Energy Load')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Record Creation Timestamp')),
            ],
            options={
                'db_table': 'household_energy_data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='householddata',
            constraint=models.UniqueConstraint(fields=('household_id',), name='unique_household_id'),
        ),
    ]
